config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  post "welcome/create" ,to: 'welcome#create', as: 'welcomes'

end

app/models/genre.rb
class Genre < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    @genres = Genre.all.map{|o| [o.name, o.id]}
  end

  def create
    p "**************begin******************"
    p 'パラメーターの出力'
    p params
    p '必要部分を配列で取り出す'
    p result = params[:genre]['name']
    result.delete('')
    p "邪魔な最初の空文字要素を外すと"
    p result
    p "***************end*******************"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SelectTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/home.html.erb
<h1>Welcome#home</h1>
<p>Find me in app/views/welcome/home.html.erb</p>

<%= form_tag(welcomes_path, method: :post) do %>
  <%= select(:genre, :name,  @genres, {},
  {multiple: true, size: '10em', name: 'genre[name][]'}) %>

<%= submit_tag "Create" %>
<% end %>